name: Deploy to Server

on:
  push:
    branches: [ main ]  # or master

jobs:
  deploy:
    runs-on: ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/AIRTC
          git pull origin main
          pm2 restart airtc