llm_model: llama3:8b

asr_model: large-v3-turbo-q8_0

tts_voice: zh-CN-XiaoxiaoNeural
tts_output: audio/tts_output.mp3
tts_subtitle: audio/tts_output.srt

english_m4a: audio/english.m4a
# wav_file: audio/english.wav
sichuanese_m4a: audio/sichuanese.m4a
# sichuanese_wav: audio/sichuanese.wav
mandarin_m4a: audio/mandarin.m4a
# mandarin_wav: audio/mandarin.wav

llm_online_model: ernie-4.5-0.3b

system_prompt: 使用中文回答问题。不要生成任何图像符号,如emoji等不属于文字的内容。

